name: baccus_kitchen
description: Kitchen application for Baccus.
publish_to: 'none'
version: 0.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Network
  dio: ^5.5.0+1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

  # Translations
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/sime_square.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/sime_square.png"
    icon_size: 48

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/
