name: baccus_kitchen
description: Kitchen application for Baccus.
publish_to: 'none'
version: 0.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Network & Serialization
  dio: ^5.5.0+1
  json_annotation: ^4.9.0

  # Local persistence
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: any
  encrypt: ^5.0.3

  # Translations
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  build_runner: ^2.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/oval_red.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path:  "assets/icon/oval_red.png"
    background_color: "#ffffff"
    theme_color: "#000000"

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/images/icon/
      - assets/images/readme/
